spring:
  profiles:
    include: real-db


  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  h2:
    console:
      enabled: true

  session:
    store-type: jdbc