server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/theplay
    username: root
    password: epicurean1!
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none

  mail:
    host: smtp.gmail.com
    port: 587
    username: todaysalcohol@gmail.com
    password: aoboykczsohchjlf
    protocol: smtp
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true


cloud:
  aws:
    credentials:
      accessKey: AKIAS5KQ3HNPX2AGCAMH
      secretKey: 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
    s3:
      bucket: theplay
    region:
      static: ap-northeast-2
    stack:
      auto: false