spring:
  profiles:
    include: real-db
  messages:
    basename: i18n/exception
    encoding: UTF-8

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true

  session:
    store-type: jdbc

  servlet:
    multipart:
      max-file-size: 50MB



