#spring.profiles.include=real-db
#spring.jpa.show_sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
#spring.h2.console.enabled=true
#spring.session.store-type=jdbc

spring:
  profiles:
    include: realdb


  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  h2:
    console:
      enabled: true

  session:
    store-type: jdbc