spring:
  profiles:
    include: real-db
  messages:
    basename: i18n/exception
    encoding: UTF-8

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  h2:
    console:
      enabled: true

  session:
    store-type: jdbc

  jwt:
    header: Authorization
    secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3
    token-validity-in-seconds : 86400